on:
 workflow_dispatch
     
jobs:
  hello:
    if: github.repository == 'muskaanbhatia30/2TierArchitecture'
    runs-on: ubuntu-latest
    steps:
      - name: current hello msg
        run: echo "hello world"
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: current bye msg
        run: echo "goodbye world"
