on:
 push:
   branches:
     - 'feature'
     
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: current time display
        run: echo "hello world , this is the multiple events workflow"
