on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: current time display
        run: echo "The current time of the server is $(date)"
